baseurl = "https://tonnidas.github.io/quantum-exercises/"  # Include trailing slash
title = "Quantum Computing"
theme = "hugo-swift-theme"
author = "Tonni Das Jui"
copyright = "Copyright Â© 2021, Tonni Das Jui; all rights reserved."
canonifyurls = true
paginate = 4
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[params]
  [params.designer]
    name = "Tonni"
    url = "https://tonnidas.github.io/"
  [[params.authors]]
    name = "Tonni" # can be nickname # if fullName ğŸ‘‡ğŸ» isn't set, name will be displayed on author card
    fullName = "Tonni Das Jui" # optional. If set, it will display on author card
    photo = "myPhotoFile.jpg"
    url = "https://tonnidas.github.io/"

[menu]
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 1

  
